// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAHAWXdyRdwRB0DaxuI_PzV07cZIeNRO0',
    appId: '1:707650694313:web:437d5c00bb1a7e293fcdb8',
    messagingSenderId: '707650694313',
    projectId: 'bbangsilgi',
    authDomain: 'bbangsilgi.firebaseapp.com',
    storageBucket: 'bbangsilgi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3FNAPEgRMB_Afs36rv2V04eAY3yFoxY',
    appId: '1:707650694313:android:70c64794186342f53fcdb8',
    messagingSenderId: '707650694313',
    projectId: 'bbangsilgi',
    storageBucket: 'bbangsilgi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-4_ZuLPHfyeXa8deUTMsL1YcRUvVnH0',
    appId: '1:707650694313:ios:0b29cf52c2b8d2723fcdb8',
    messagingSenderId: '707650694313',
    projectId: 'bbangsilgi',
    storageBucket: 'bbangsilgi.firebasestorage.app',
    iosBundleId: 'com.jylee.bakingGuide',
  );
}
