# -*- coding: utf-8 -*-
"""제과기능사 과자·케이크 20종 — raw_images JPG 추출 스펙 (JSON 생성용)."""

CONFECTIONERY_SPECS = [
    {
        "id": "butter_cookie",
        "name": "버터쿠키",
        "category": "cookie",
        "examTimeSec": 7200,
        "mixingMethod": "cream",
        "oven": {"top": 200, "bottom": 140, "unit": "celsius", "timeSec": 660},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 400, "unit": "g", "category": "flour", "weighGroupId": "dry_powder"},
            {"name": "버터", "amount": 280, "unit": "g", "category": "fat"},
            {"name": "설탕", "amount": 200, "unit": "g", "category": "sweetener"},
            {"name": "소금", "amount": 4, "unit": "g", "category": "salt"},
            {"name": "달걀", "amount": 120, "unit": "g", "category": "egg"},
            {"name": "바닐라향", "amount": 2, "unit": "g", "category": "spice", "weighGroupId": "dry_powder"},
        ],
        "weighGroups": [{"id": "dry_powder", "label": "가루류·합침 가능"}],
        "weighNotes": "계량 6분(재료당 약 1분). 달걀은 감독 지시 수량.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간", "구움 과자류", "반죽형 쿠키·크림법(수작업)"]},
            {"title": "반죽", "items": ["크림법", "반죽온도 22℃", "가루 90% 혼합"]},
            {"title": "성형", "items": ["별 깍지", "8자·장미", "반죽 전량"]},
            {"title": "굽기", "items": ["200/140℃", "10~12분", "바닥 과색 주의"]},
            {"title": "주요 감점 포인트", "items": ["모양·크기·두께 불균일", "바닥 과다 착색"]},
        ],
        "steps": [
            {"title": "01. 재료 계량", "description": ["6분 내 계량·진열", "달걀은 감독 지시"], "estimatedTimeSec": 360},
            {"title": "02. 버터 크림화", "description": ["버터 부드럽게 풀기"], "estimatedTimeSec": 300},
            {"title": "03. 설탕·소금", "description": ["설탕·소금 혼합", "설탕 과다 용해 방지"], "estimatedTimeSec": 240},
            {"title": "04. 달걀 투입", "description": ["달걀 나누어 크림화"], "estimatedTimeSec": 300},
            {"title": "05. 가루 혼합", "description": ["체질 가루 가볍게", "글루텐 형성 방지"], "estimatedTimeSec": 240},
            {"title": "06. 반죽 완성", "description": ["90% 혼합", "반죽온 22℃"], "estimatedTimeSec": 180},
            {"title": "07. 짤주머니", "description": ["별 깍지", "오븐 예열·체질"], "estimatedTimeSec": 180},
            {"title": "08. 장미 성형", "description": ["장미 모양 짜기", "간격·두께 균일"], "estimatedTimeSec": 600},
            {"title": "09. 8자 성형", "description": ["S자 8자", "반죽 전량"], "estimatedTimeSec": 600},
            {"title": "10. 굽기", "description": ["200/140℃ 10~12분"], "estimatedTimeSec": 660, "timers": [{"type": "baking", "label": "굽기", "durationSec": 660}]},
        ],
        "resultEvaluation": [
            {"id": "color", "text": "전체 황금갈색"},
            {"id": "shape", "text": "8자·장미 선명"},
            {"id": "uniformity", "text": "크기·두께 균일"},
        ],
        "difficulty": 2,
    },
    {
        "id": "fruit_cake",
        "name": "과일케이크",
        "category": "cake",
        "examTimeSec": 9000,
        "mixingMethod": "separated_egg",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 2100, "notes": "이중팬 180℃"},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 500, "unit": "g", "category": "flour"},
            {"name": "설탕", "amount": 450, "unit": "g", "category": "sweetener"},
            {"name": "마가린", "amount": 276, "unit": "g", "category": "fat"},
            {"name": "달걀", "amount": 500, "unit": "g", "category": "egg"},
            {"name": "우유", "amount": 90, "unit": "g", "category": "liquid"},
            {"name": "베이킹파우더", "amount": 5, "unit": "g", "category": "powder"},
            {"name": "소금", "amount": 8, "unit": "g", "category": "salt"},
            {"name": "건포도", "amount": 76, "unit": "g", "category": "filling"},
            {"name": "체리", "amount": 150, "unit": "g", "category": "filling"},
            {"name": "호두", "amount": 100, "unit": "g", "category": "filling"},
            {"name": "오렌지필", "amount": 66, "unit": "g", "category": "filling"},
            {"name": "럼주", "amount": 80, "unit": "g", "category": "liquid"},
            {"name": "바닐라향", "amount": 2, "unit": "g", "category": "spice"},
        ],
        "weighNotes": "계량 13분. 설탕 2등분(노른자/머랭).",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간 30분", "복합형(크림+별립)", "계량 13분"]},
            {"title": "반죽", "items": ["별립법", "반죽온 23℃", "머랭 중간피크"]},
            {"title": "성형", "items": ["파운드틀 60~70%", "3~4개 팬닝", "과일 밀가루 코팅"]},
            {"title": "굽기", "items": ["180/160℃ 30~40분", "이중팬 180℃"]},
            {"title": "주요 감점 포인트", "items": ["과일 침적", "중심 미숙", "균열·함몰"]},
        ],
        "steps": [
            {"title": "01. 계량·분리", "description": ["13분 계량", "노른자·흰자 분리"], "estimatedTimeSec": 780},
            {"title": "02. 체리·과일 전처리", "description": ["체리 건포도 크기", "럼주 전처리", "호두 오븐 구움"], "estimatedTimeSec": 600},
            {"title": "03~06. 크림·머랭", "description": ["마가린+설탕50%+소금", "노른자 3~4회", "머랭 중간피크"], "estimatedTimeSec": 900},
            {"title": "07~08. 과일·가루", "description": ["과일+호두 밀가루 코팅", "머랭 1/3→가루→우유→머랭2/3"], "estimatedTimeSec": 600},
            {"title": "09~10. 팬닝", "description": ["파운드틀 60~70%", "가운데 평평·양끝 각지게"], "estimatedTimeSec": 480},
            {"title": "11. 굽기", "description": ["180/160℃ 30~40분"], "estimatedTimeSec": 2100, "timers": [{"type": "baking", "label": "굽기", "durationSec": 2100}]},
        ],
        "resultEvaluation": [
            {"id": "doneness", "text": "균일 팬닝·완전 굽기"},
            {"id": "fruit", "text": "과일 고르게 분포"},
            {"id": "appearance", "text": "4개 대칭·균열·함몰 없음"},
        ],
        "difficulty": 4,
    },
    {
        "id": "dacquoise",
        "name": "다쿠와즈",
        "category": "cookie",
        "examTimeSec": 6600,
        "mixingMethod": "meringue",
        "oven": {"top": 190, "bottom": 160, "unit": "celsius", "timeSec": 1050},
        "fermentation": {},
        "ingredients": [
            {"name": "달걀 흰자", "amount": 326, "unit": "g", "category": "egg"},
            {"name": "설탕", "amount": 100, "unit": "g", "category": "sweetener"},
            {"name": "아몬드 분말", "amount": 200, "unit": "g", "category": "powder"},
            {"name": "분당", "amount": 166, "unit": "g", "category": "sweetener"},
            {"name": "박력분", "amount": 50, "unit": "g", "category": "flour"},
            {"name": "버터크림(샌드용)", "amount": 226, "unit": "g", "category": "filling"},
        ],
        "weighNotes": "계량 5분. 충전용(버터크림)은 굽기 중 계량.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "거품형 쿠키·머랭법"]},
            {"title": "반죽", "items": ["머랭 중간피크", "가루 2회 체질", "과혼합 금지"]},
            {"title": "성형", "items": ["다쿠와즈팬", "분당 2회", "반죽 전량"]},
            {"title": "굽기", "items": ["190/160℃ 15~20분", "표피 갈라짐"]},
            {"title": "주요 감점 포인트", "items": ["두께·크기 불균일", "반죽 질음·옆 퍼짐"]},
        ],
        "steps": [
            {"title": "01. 계량", "description": ["5분 계량", "흰자 분리"], "estimatedTimeSec": 300},
            {"title": "02~05. 머랭·혼합", "description": ["가루 2회 체질", "머랭→가루 가볍게"], "estimatedTimeSec": 600},
            {"title": "06~08. 짜기", "description": ["짤주머니", "실리콘+다쿠와즈팬"], "estimatedTimeSec": 480},
            {"title": "09~11. 마무리·굽기", "description": ["스크래퍼 평탄", "분당 2회", "190/160℃ 15~20분"], "estimatedTimeSec": 1050},
            {"title": "12. 샌드", "description": ["식힌 후 크림 2개 붙임"], "estimatedTimeSec": 300},
        ],
        "resultEvaluation": [
            {"id": "uniformity", "text": "두께·크기 균일"},
            {"id": "surface", "text": "윗면 갈라짐·옆면 익음"},
            {"id": "batter", "text": "반죽 질지 않음"},
        ],
        "difficulty": 3,
    },
    {
        "id": "madera_cake",
        "name": "마데라(컵)케이크",
        "category": "cake",
        "examTimeSec": 7200,
        "mixingMethod": "cream",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 1650, "dryTopSec": 150},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 400, "unit": "g", "category": "flour"},
            {"name": "버터", "amount": 340, "unit": "g", "category": "fat"},
            {"name": "설탕", "amount": 320, "unit": "g", "category": "sweetener"},
            {"name": "소금", "amount": 4, "unit": "g", "category": "salt"},
            {"name": "달걀", "amount": 340, "unit": "g", "category": "egg"},
            {"name": "베이킹파우더", "amount": 10, "unit": "g", "category": "powder"},
            {"name": "건포도", "amount": 100, "unit": "g", "category": "filling"},
            {"name": "호두", "amount": 40, "unit": "g", "category": "filling"},
            {"name": "적포도주", "amount": 120, "unit": "g", "category": "liquid"},
            {"name": "분당", "amount": 80, "unit": "g", "category": "sweetener"},
            {"name": "적포도주 시럽", "amount": 20, "unit": "g", "category": "liquid"},
        ],
        "weighNotes": "계량 9분. 퐁당 재료는 굽기 중(머핀 90% 시점).",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간", "크림법", "계량 9분"]},
            {"title": "반죽", "items": ["반죽온 24℃", "건포도 적포도주 전처리"]},
            {"title": "성형", "items": ["머핀팬 70%", "퐁당 1회"]},
            {"title": "굽기", "items": ["180/160℃ 25~30분", "180℃ 2~3분 건조"]},
            {"title": "주요 감점 포인트", "items": ["건포도·호두 침적", "윗면 터짐"]},
        ],
        "steps": [
            {"title": "01~04. 크림화", "description": ["계량", "건포도 전처리", "버터·설탕·달걀 크림"], "estimatedTimeSec": 900},
            {"title": "05~08. 충전물", "description": ["건포도·호두 밀가루", "가루·적포도주"], "estimatedTimeSec": 480},
            {"title": "09~12. 팬닝·굽기", "description": ["머핀 70%", "180/160℃ 25~30분"], "estimatedTimeSec": 1800},
            {"title": "13~15. 퐁당", "description": ["분당80+시럽20", "윗면 발라 180℃ 2~3분"], "estimatedTimeSec": 300},
        ],
        "resultEvaluation": [
            {"id": "shape", "text": "크기 균일·윗면 둥글게"},
            {"id": "filling", "text": "건포도·호두 고르게"},
            {"id": "texture", "text": "견과 침적·윗면 터짐 없음"},
        ],
        "difficulty": 3,
    },
    {
        "id": "madeleine",
        "name": "마드레느",
        "category": "specialty",
        "examTimeSec": 6600,
        "mixingMethod": "one_stage",
        "oven": {"top": 180, "bottom": 150, "unit": "celsius", "timeSec": 900},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 400, "unit": "g", "category": "flour"},
            {"name": "베이킹파우더", "amount": 8, "unit": "g", "category": "powder"},
            {"name": "설탕", "amount": 400, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 400, "unit": "g", "category": "egg"},
            {"name": "레몬껍질", "amount": 4, "unit": "g", "category": "spice"},
            {"name": "소금", "amount": 2, "unit": "g", "category": "salt"},
            {"name": "버터", "amount": 400, "unit": "g", "category": "fat"},
        ],
        "weighNotes": "계량 7분. 수작업.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "1단계법(변형)", "수작업"]},
            {"title": "반죽", "items": ["용해버터 2~3회", "기포 최소", "반죽온 24℃"]},
            {"title": "성형", "items": ["실온 휴지 15~20분", "팬 80%", "유지 바르기"]},
            {"title": "굽기", "items": ["180/150℃ 약 15분"]},
            {"title": "주요 감점 포인트", "items": ["날개 과다", "윗면 과평탄"]},
        ],
        "steps": [
            {"title": "01~08. 반죽", "description": ["계량", "레몬껍질", "중탕 버터", "가루+달걀+버터"], "estimatedTimeSec": 1200},
            {"title": "09~12. 휴지·성형", "description": ["휴지 15~20분", "팬 유지", "80% 짜기"], "estimatedTimeSec": 1200},
            {"title": "13~14. 굽기", "description": ["180/150℃ 15분", "분리"], "estimatedTimeSec": 900},
        ],
        "resultEvaluation": [
            {"id": "color", "text": "황금갈색"},
            {"id": "shape", "text": "가운데 솟음·날개 적절"},
            {"id": "crumb", "text": "기공 과다 없음"},
        ],
        "difficulty": 2,
    },
    {
        "id": "butter_sponge_cake_gongrip",
        "name": "버터스펀지케이크(공립법)",
        "category": "cake",
        "examTimeSec": 6600,
        "mixingMethod": "sponge",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 1650},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 500, "unit": "g", "category": "flour"},
            {"name": "설탕", "amount": 600, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 900, "unit": "g", "category": "egg"},
            {"name": "소금", "amount": 5, "unit": "g", "category": "salt"},
            {"name": "바닐라향", "amount": 2.5, "unit": "g", "category": "spice"},
            {"name": "버터", "amount": 100, "unit": "g", "category": "fat"},
        ],
        "weighNotes": "계량 6분. 비중 0.5±0.05. 원형팬 3호 4개.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "공립법", "계량 6분"]},
            {"title": "반죽", "items": ["중탕 43~50℃", "아이보리 거품", "비중 0.5±0.05"]},
            {"title": "성형", "items": ["팬 50~60%", "펀칭"]},
            {"title": "굽기", "items": ["180/160℃ 25~30분"]},
            {"title": "주요 감점 포인트", "items": ["윗면 갈라짐", "기공 과다", "버터 뭉침"]},
        ],
        "steps": [
            {"title": "01~03. 거품", "description": ["계량", "달걀+설탕 중탕", "고속→중속 안정화"], "estimatedTimeSec": 600},
            {"title": "04~08. 혼합", "description": ["버터 60℃", "가루 접기", "버터 혼합"], "estimatedTimeSec": 480},
            {"title": "09~11. 굽기", "description": ["50~60% 팬닝", "펀칭", "180/160℃ 25~30분"], "estimatedTimeSec": 1800},
        ],
        "resultEvaluation": [
            {"id": "surface", "text": "과도한 갈라짐·기공 없음"},
            {"id": "volume", "text": "4개 부피 균일"},
            {"id": "crumb", "text": "버터 고르게·황금갈색"},
        ],
        "difficulty": 4,
    },
    {
        "id": "butter_sponge_cake_separated",
        "name": "버터스펀지케이크(별립법)",
        "category": "cake",
        "examTimeSec": 6600,
        "mixingMethod": "separated_egg",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 1800},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 600, "unit": "g", "category": "flour"},
            {"name": "설탕 A", "amount": 360, "unit": "g", "category": "sweetener"},
            {"name": "설탕 B", "amount": 360, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 900, "unit": "g", "category": "egg"},
            {"name": "소금", "amount": 9, "unit": "g", "category": "salt"},
            {"name": "베이킹파우더", "amount": 6, "unit": "g", "category": "powder"},
            {"name": "바닐라향", "amount": 3, "unit": "g", "category": "spice"},
            {"name": "용해버터", "amount": 150, "unit": "g", "category": "fat"},
        ],
        "weighNotes": "계량 8분. 설탕 A/B 분리. 비중 0.5±0.05.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "별립법", "반죽온 23℃"]},
            {"title": "반죽", "items": ["머랭 중간피크", "용해버터 과혼합 금지"]},
            {"title": "성형", "items": ["50~60% 팬닝", "펀칭"]},
            {"title": "굽기", "items": ["180/160℃ 30분 전후"]},
            {"title": "주요 감점 포인트", "items": ["4개 부피 불균", "함몰·갈라짐"]},
        ],
        "steps": [
            {"title": "01~04. 머랭", "description": ["계량·분리", "노른자+설탕A", "머랭"], "estimatedTimeSec": 720},
            {"title": "05~09. 혼합", "description": ["머랭 1/3→가루→버터", "머랭 2/3"], "estimatedTimeSec": 600},
            {"title": "10~12. 굽기", "description": ["비중 확인", "펀칭", "180/160℃ 30분"], "estimatedTimeSec": 1800},
        ],
        "resultEvaluation": [
            {"id": "volume", "text": "4개 부피 균일"},
            {"id": "surface", "text": "솟음·갈라짐·검은점 없음"},
            {"id": "crumb", "text": "함몰 없음·버터 균일"},
        ],
        "difficulty": 4,
    },
    {
        "id": "brownie",
        "name": "브라우니",
        "category": "cake",
        "examTimeSec": 6600,
        "mixingMethod": "one_stage",
        "oven": {"top": 170, "bottom": 150, "unit": "celsius", "timeSec": 2700, "notes": "이중팬 170℃"},
        "fermentation": {},
        "ingredients": [
            {"name": "중력분", "amount": 300, "unit": "g", "category": "flour"},
            {"name": "달걀", "amount": 360, "unit": "g", "category": "egg"},
            {"name": "설탕", "amount": 390, "unit": "g", "category": "sweetener"},
            {"name": "소금", "amount": 6, "unit": "g", "category": "salt"},
            {"name": "버터", "amount": 150, "unit": "g", "category": "fat"},
            {"name": "다크초콜릿", "amount": 450, "unit": "g", "category": "filling"},
            {"name": "코코아파우더", "amount": 30, "unit": "g", "category": "powder"},
            {"name": "바닐라향", "amount": 6, "unit": "g", "category": "spice"},
            {"name": "호두", "amount": 150, "unit": "g", "category": "filling"},
        ],
        "weighNotes": "계량 9분. 수작업. 호두 1/2 내부·1/2 토핑.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "1단계법(변형)", "반죽온 27℃"]},
            {"title": "반죽", "items": ["초코+버터 50℃", "과혼합·고온 금지"]},
            {"title": "성형", "items": ["원형팬 3호 2개", "호두 토핑"]},
            {"title": "굽기", "items": ["170/150℃ 40~50분"]},
            {"title": "주요 감점 포인트", "items": ["함몰", "내부 묻어남", "맨홀"]},
        ],
        "steps": [
            {"title": "01~07. 반죽", "description": ["계량", "호두 구움", "초코중탕", "달걀+가루+호두1/2"], "estimatedTimeSec": 1200},
            {"title": "08~10. 굽기", "description": ["2팬 팬닝", "호두 토핑", "170/150℃ 40~50분"], "estimatedTimeSec": 2700},
        ],
        "resultEvaluation": [
            {"id": "structure", "text": "함몰·기포 없음"},
            {"id": "doneness", "text": "내부 묻어남 없음"},
            {"id": "color", "text": "짙은 초콜릿색·호두 고르게"},
        ],
        "difficulty": 3,
    },
    {
        "id": "shortbread_cookie",
        "name": "쇼트브레드 쿠키",
        "category": "cookie",
        "examTimeSec": 7200,
        "mixingMethod": "cream",
        "oven": {"top": 200, "bottom": 160, "unit": "celsius", "timeSec": 810},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 500, "unit": "g", "category": "flour"},
            {"name": "마가린", "amount": 166, "unit": "g", "category": "fat"},
            {"name": "쇼트닝", "amount": 166, "unit": "g", "category": "fat"},
            {"name": "설탕", "amount": 176, "unit": "g", "category": "sweetener"},
            {"name": "소금", "amount": 6, "unit": "g", "category": "salt"},
            {"name": "물엿", "amount": 26, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 50, "unit": "g", "category": "egg"},
            {"name": "달걀 노른자", "amount": 50, "unit": "g", "category": "egg"},
            {"name": "바닐라향", "amount": 2, "unit": "g", "category": "spice"},
        ],
        "weighNotes": "계량 9분. 달걀7개 제공(반죽4+발림3). 반죽온 20℃.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간", "크림법 수작업", "두께 0.7~0.8cm"]},
            {"title": "반죽", "items": ["냉장 휴지 20~30분", "과크림화 금지"]},
            {"title": "성형", "items": ["지름 5~6cm", "2팬", "노른자 2회·포크무늬"]},
            {"title": "굽기", "items": ["200/160℃ 12~15분"]},
            {"title": "주요 감점 포인트", "items": ["두께·모양 불균", "무늬 불선명"]},
        ],
        "steps": [
            {"title": "01~08. 반죽", "description": ["계량", "크림화", "냉장휴지 20~30분"], "estimatedTimeSec": 1500},
            {"title": "09~14. 성형·굽기", "description": ["밀기 0.7~0.8cm", "컷팅", "노른자·무늬", "200/160℃ 12~15분"], "estimatedTimeSec": 1200},
        ],
        "resultEvaluation": [
            {"id": "uniformity", "text": "두께·모양 균일"},
            {"id": "color", "text": "윗면 황금·밑면 과진 않음"},
            {"id": "pattern", "text": "포크무늬 선명"},
        ],
        "difficulty": 3,
    },
    {
        "id": "soft_roll_cake",
        "name": "소프트롤케이크",
        "category": "cake",
        "examTimeSec": 6600,
        "mixingMethod": "separated_egg",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 1200},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 250, "unit": "g", "category": "flour"},
            {"name": "설탕 A", "amount": 176, "unit": "g", "category": "sweetener"},
            {"name": "물엿", "amount": 26, "unit": "g", "category": "sweetener"},
            {"name": "소금", "amount": 2, "unit": "g", "category": "salt"},
            {"name": "물", "amount": 50, "unit": "g", "category": "liquid"},
            {"name": "바닐라향", "amount": 2, "unit": "g", "category": "spice"},
            {"name": "설탕 B", "amount": 150, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 700, "unit": "g", "category": "egg"},
            {"name": "베이킹파우더", "amount": 2, "unit": "g", "category": "powder"},
            {"name": "식용유", "amount": 126, "unit": "g", "category": "fat"},
            {"name": "잼", "amount": 200, "unit": "g", "category": "filling"},
        ],
        "weighNotes": "계량 10분. 비중 0.5±0.05. 캐러멜 무늬 필수(미완 시 0점).",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "별립법", "반죽온 22℃"]},
            {"title": "반죽", "items": ["식용유 희석 혼합", "비중 0.5±0.05"]},
            {"title": "성형", "items": ["캐러멜 3cm 간격 무늬", "잼 말기"]},
            {"title": "굽기", "items": ["180/160℃ 약 20분"]},
            {"title": "주요 감점 포인트", "items": ["무늬 불균형", "내부 기공", "과밀 말기"]},
        ],
        "steps": [
            {"title": "01~08. 반죽", "description": ["계량·분리", "노른자+물엿", "머랭", "유+가루"], "estimatedTimeSec": 1200},
            {"title": "09~15. 무늬·굽기·말기", "description": ["팬닝·캐러멜무늬", "굽기", "젖은 면포·잼·말기"], "estimatedTimeSec": 1800},
        ],
        "resultEvaluation": [
            {"id": "holes", "text": "내부 기공 없음"},
            {"id": "pattern", "text": "캐러멜 무늬 대칭"},
            {"id": "roll", "text": "부피·갈라짐 없이 말기"},
        ],
        "difficulty": 4,
    },
    {
        "id": "choux",
        "name": "슈",
        "category": "pastry",
        "examTimeSec": 7200,
        "mixingMethod": "choux_paste",
        "oven": {"top": 180, "bottom": 200, "unit": "celsius", "timeSec": 2400, "notes": "10분 후 아랫불 160℃"},
        "fermentation": {},
        "ingredients": [
            {"name": "중력분", "amount": 200, "unit": "g", "category": "flour"},
            {"name": "물", "amount": 250, "unit": "g", "category": "liquid"},
            {"name": "버터", "amount": 200, "unit": "g", "category": "fat"},
            {"name": "소금", "amount": 2, "unit": "g", "category": "salt"},
            {"name": "달걀", "amount": 400, "unit": "g", "category": "egg"},
            {"name": "커스터드 크림", "amount": 1000, "unit": "g", "category": "filling"},
        ],
        "weighNotes": "계량 5분. 껍질 수작업. 충전 크림은 굽기 중 계량.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간", "전분 호화 반죽", "지름 3cm"]},
            {"title": "반죽", "items": ["호화 충분", "달걀 양 조절", "수작업"]},
            {"title": "성형", "items": ["물 스프레이", "반죽 전량"]},
            {"title": "굽기", "items": ["180/200→160℃ 총 40분", "갈라진 부분 색"]},
            {"title": "주요 감점 포인트", "items": ["바닥 퍼짐", "일찍 꺼내 함몰", "속 미건조"]},
        ],
        "steps": [
            {"title": "01~08. 반죽", "description": ["계량", "끓여 호화", "달걀 단계", "3cm 짜기"], "estimatedTimeSec": 900},
            {"title": "09~14. 굽기·충전", "description": ["스프레이", "180/200→160℃", "크림 충전"], "estimatedTimeSec": 2700},
        ],
        "resultEvaluation": [
            {"id": "shape", "text": "모양·크기 균일·바삭"},
            {"id": "batter", "text": "바닥 퍼짐·함몰 없음"},
            {"id": "interior", "text": "속 공갈·건조"},
        ],
        "difficulty": 4,
    },
    {
        "id": "chiffon_cake",
        "name": "시퐁케이크",
        "category": "cake",
        "examTimeSec": 6000,
        "mixingMethod": "chiffon",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 1800},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 400, "unit": "g", "category": "flour"},
            {"name": "설탕 A", "amount": 260, "unit": "g", "category": "sweetener"},
            {"name": "설탕 B", "amount": 260, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 600, "unit": "g", "category": "egg"},
            {"name": "소금", "amount": 6, "unit": "g", "category": "salt"},
            {"name": "베이킹파우더", "amount": 10, "unit": "g", "category": "powder"},
            {"name": "식용유", "amount": 160, "unit": "g", "category": "fat"},
            {"name": "물", "amount": 120, "unit": "g", "category": "liquid"},
        ],
        "weighNotes": "계량 8분. 비중 0.5±0.05. 시퐁팬 4개.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 40분", "시폰법", "반죽온 23℃"]},
            {"title": "반죽", "items": ["노른자 거품 최소", "머랭 80%"]},
            {"title": "성형", "items": ["팬 60%", "즉시 뒤집기"]},
            {"title": "굽기", "items": ["180/160℃ 30분", "물 뿌려 냉각"]},
            {"title": "주요 감점 포인트", "items": ["함몰", "옆면 눌림", "부피 불균"]},
        ],
        "steps": [
            {"title": "01~08. 반죽", "description": ["계량·분리", "팬 스프레이", "노른자+유+물", "머랭 접기"], "estimatedTimeSec": 1200},
            {"title": "09~13. 굽기·완성", "description": ["60% 팬닝", "굽기", "뒤집기·냉각·탈형"], "estimatedTimeSec": 2400},
        ],
        "resultEvaluation": [
            {"id": "surface", "text": "끈적·함몰 없음"},
            {"id": "shape", "text": "기공·옆면 손상 없음"},
            {"id": "volume", "text": "4개 부피 균일·연한 황색"},
        ],
        "difficulty": 4,
    },
    {
        "id": "jelly_roll_cake",
        "name": "젤리롤케이크",
        "category": "cake",
        "examTimeSec": 5400,
        "mixingMethod": "sponge",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 1350},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 400, "unit": "g", "category": "flour"},
            {"name": "설탕", "amount": 520, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 680, "unit": "g", "category": "egg"},
            {"name": "소금", "amount": 8, "unit": "g", "category": "salt"},
            {"name": "물엿", "amount": 32, "unit": "g", "category": "sweetener"},
            {"name": "베이킹파우더", "amount": 2, "unit": "g", "category": "powder"},
            {"name": "우유", "amount": 80, "unit": "g", "category": "liquid"},
            {"name": "바닐라향", "amount": 4, "unit": "g", "category": "spice"},
            {"name": "잼", "amount": 200, "unit": "g", "category": "filling"},
        ],
        "weighNotes": "계량 8분. 비중 0.5±0.05. 캐러멜 무늬 필수.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 30분", "공립법", "반죽온 23℃"]},
            {"title": "반죽", "items": ["중탕 43~50℃", "아이보리 거품"]},
            {"title": "성형", "items": ["캐러멜 3cm 무늬", "젖은 면포 말기"]},
            {"title": "굽기", "items": ["180/160℃ 20~25분"]},
            {"title": "주요 감점 포인트", "items": ["내부 빈틈", "무늬 불균", "과밀 말기"]},
        ],
        "steps": [
            {"title": "01~08. 반죽·무늬", "description": ["계량", "중탕 거품", "가루·우유", "캐러멜 무늬"], "estimatedTimeSec": 1200},
            {"title": "09~14. 굽기·말기", "description": ["굽기", "뒤집기", "잼·말기"], "estimatedTimeSec": 1800},
        ],
        "resultEvaluation": [
            {"id": "holes", "text": "내부 빈틈 없음"},
            {"id": "pattern", "text": "캐러멜 대칭·균열 없음"},
            {"id": "volume", "text": "부피·뭉침 없음"},
        ],
        "difficulty": 3,
    },
    {
        "id": "choco_roll_cake",
        "name": "초코롤케이크",
        "category": "cake",
        "examTimeSec": 6600,
        "mixingMethod": "sponge",
        "oven": {"top": 190, "bottom": 160, "unit": "celsius", "timeSec": 750, "notes": "이중팬 180℃"},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 168, "unit": "g", "category": "flour"},
            {"name": "달걀", "amount": 480, "unit": "g", "category": "egg"},
            {"name": "설탕", "amount": 216, "unit": "g", "category": "sweetener"},
            {"name": "코코아파우더", "amount": 36, "unit": "g", "category": "powder"},
            {"name": "베이킹소다", "amount": 2, "unit": "g", "category": "improver"},
            {"name": "물", "amount": 12, "unit": "g", "category": "liquid"},
            {"name": "우유", "amount": 30, "unit": "g", "category": "liquid"},
            {"name": "다크커버춰", "amount": 200, "unit": "g", "category": "filling"},
            {"name": "생크림", "amount": 200, "unit": "g", "category": "filling"},
            {"name": "럼주", "amount": 20, "unit": "g", "category": "spice"},
        ],
        "weighNotes": "계량 7분. 가나슈는 굽기 중. 말기 방향 감독 지시.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "공립법", "반죽온 24℃"]},
            {"title": "반죽", "items": ["비중 0.5±0.05", "오버베이킹 금지"]},
            {"title": "성형", "items": ["구운 윗면에 가나슈", "원형 말기"]},
            {"title": "굽기", "items": ["190/160℃ 10~15분"]},
            {"title": "주요 감점 포인트", "items": ["코코아 뭉침", "내부 구멍", "갈라짐"]},
        ],
        "steps": [
            {"title": "01~07. 시트", "description": ["계량", "중탕 거품", "가루·굽기", "면포 덮기"], "estimatedTimeSec": 1200},
            {"title": "08~13. 가나슈·말기", "description": ["가나슈 40~45℃", "잼 대신 윗면 발라 말기"], "estimatedTimeSec": 1200},
        ],
        "resultEvaluation": [
            {"id": "surface", "text": "코코아 뭉침 없음"},
            {"id": "crumb", "text": "내부 구멍 없음"},
            {"id": "roll", "text": "두께 균일·갈라짐 없음"},
        ],
        "difficulty": 4,
    },
    {
        "id": "choco_muffin",
        "name": "초코머핀",
        "category": "cake",
        "examTimeSec": 6600,
        "mixingMethod": "cream",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 1650},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 500, "unit": "g", "category": "flour"},
            {"name": "설탕", "amount": 300, "unit": "g", "category": "sweetener"},
            {"name": "버터", "amount": 300, "unit": "g", "category": "fat"},
            {"name": "달걀", "amount": 300, "unit": "g", "category": "egg"},
            {"name": "소금", "amount": 5, "unit": "g", "category": "salt"},
            {"name": "베이킹소다", "amount": 2, "unit": "g", "category": "improver"},
            {"name": "베이킹파우더", "amount": 8, "unit": "g", "category": "powder"},
            {"name": "코코아파우더", "amount": 60, "unit": "g", "category": "powder"},
            {"name": "물", "amount": 175, "unit": "g", "category": "liquid"},
            {"name": "탈지분유", "amount": 30, "unit": "g", "category": "powder"},
            {"name": "초코칩", "amount": 180, "unit": "g", "category": "filling"},
        ],
        "weighNotes": "계량 11분. 반죽온 24℃. 초코칩 균일 분포.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "크림법", "11재료 11분"]},
            {"title": "반죽", "items": ["크림화 후 초코칩", "접기 혼합"]},
            {"title": "성형", "items": ["머핀 70%", "반죽 전량"]},
            {"title": "굽기", "items": ["180/160℃ 25~30분"]},
            {"title": "주요 감점 포인트", "items": ["짤주머니 새어나옴", "부피 불균"]},
        ],
        "steps": [
            {"title": "01~08. 반죽", "description": ["계량", "크림화", "초코칩", "가루+물 접기"], "estimatedTimeSec": 1200},
            {"title": "09~11. 굽기", "description": ["70% 팬닝", "180/160℃ 25~30분"], "estimatedTimeSec": 1800},
        ],
        "resultEvaluation": [
            {"id": "volume", "text": "부피·크기 균일"},
            {"id": "top", "text": "윗면 둥글게"},
            {"id": "chips", "text": "초코칩 고르게·부드러움"},
        ],
        "difficulty": 3,
    },
    {
        "id": "cheesecake",
        "name": "치즈케이크",
        "category": "cake",
        "examTimeSec": 9000,
        "mixingMethod": "separated_egg",
        "oven": {"top": 150, "bottom": 150, "unit": "celsius", "timeSec": 3000, "notes": "중탕(평철판 1/3 물)"},
        "fermentation": {},
        "ingredients": [
            {"name": "중력분", "amount": 80, "unit": "g", "category": "flour"},
            {"name": "버터", "amount": 80, "unit": "g", "category": "fat"},
            {"name": "설탕 A", "amount": 80, "unit": "g", "category": "sweetener"},
            {"name": "설탕 B", "amount": 80, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 240, "unit": "g", "category": "egg"},
            {"name": "크림치즈", "amount": 400, "unit": "g", "category": "filling"},
            {"name": "우유", "amount": 130, "unit": "g", "category": "liquid"},
            {"name": "럼주", "amount": 10, "unit": "g", "category": "liquid"},
            {"name": "레몬주스", "amount": 20, "unit": "g", "category": "liquid"},
        ],
        "weighNotes": "계량 9분. 비중 0.7±0.05. 중탕 굽기.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간 30분", "별립법+크림치즈", "반죽온 20℃"]},
            {"title": "반죽", "items": ["머랭 70%", "건조피크 금지"]},
            {"title": "성형", "items": ["팬 버터·설탕", "80% 팬닝"]},
            {"title": "굽기", "items": ["150/150℃ 50분 중탕"]},
            {"title": "주요 감점 포인트", "items": ["윗면 갈라짐", "함몰", "거친 기공"]},
        ],
        "steps": [
            {"title": "01~08. 반죽", "description": ["계량·분리", "팬 코팅", "크림치즈+노른자", "머랭 70%"], "estimatedTimeSec": 1200},
            {"title": "09~14. 굽기", "description": ["머랭 접기", "80% 팬닝", "중탕 50분", "배열"], "estimatedTimeSec": 3600},
        ],
        "resultEvaluation": [
            {"id": "top", "text": "윗면 약간 솟음·갈라짐 없음"},
            {"id": "crumb", "text": "매끈·촉촉"},
            {"id": "volume", "text": "부피 균일·함몰 없음"},
        ],
        "difficulty": 5,
    },
    {
        "id": "tart",
        "name": "타르트",
        "category": "pastry",
        "examTimeSec": 8400,
        "mixingMethod": "cream",
        "oven": {"top": 180, "bottom": 200, "unit": "celsius", "timeSec": 1800, "notes": "10분 후 아랫불 220℃"},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 400, "unit": "g", "category": "flour"},
            {"name": "달걀", "amount": 100, "unit": "g", "category": "egg"},
            {"name": "설탕", "amount": 104, "unit": "g", "category": "sweetener"},
            {"name": "버터", "amount": 160, "unit": "g", "category": "fat"},
            {"name": "소금", "amount": 2, "unit": "g", "category": "salt"},
            {"name": "아몬드 분말", "amount": 250, "unit": "g", "category": "powder"},
            {"name": "설탕(충전)", "amount": 226, "unit": "g", "category": "sweetener"},
            {"name": "버터(충전)", "amount": 250, "unit": "g", "category": "fat"},
            {"name": "달걀(충전)", "amount": 162, "unit": "g", "category": "egg"},
            {"name": "브랜디", "amount": 30, "unit": "g", "category": "liquid"},
            {"name": "에프리코트혼당", "amount": 150, "unit": "g", "category": "filling"},
            {"name": "물", "amount": 60, "unit": "g", "category": "liquid"},
            {"name": "아몬드슬라이스", "amount": 100, "unit": "g", "category": "filling"},
        ],
        "weighNotes": "반죽 계량 5분. 충전·토핑은 휴지 중. 8개 제조.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간 20분", "크림법", "반죽온 20℃"]},
            {"title": "반죽", "items": ["냉장휴지 20~30분", "두께 3mm"]},
            {"title": "성형", "items": ["Ø10~12cm 60~70%", "아몬드슬라이스"]},
            {"title": "굽기", "items": ["180/200→220℃", "뜨거울 때 광택제"]},
            {"title": "주요 감점 포인트", "items": ["수축", "맨홀", "겉·바닥 두께 불균"]},
        ],
        "steps": [
            {"title": "01~05. 반죽", "description": ["크림법", "냉장휴지"], "estimatedTimeSec": 900},
            {"title": "06~09. 충전", "description": ["아몬드크림", "브랜디"], "estimatedTimeSec": 600},
            {"title": "10~15. 성형·굽기", "description": ["3mm 밀기", "짜기·토핑", "굽기·광택"], "estimatedTimeSec": 2400},
        ],
        "resultEvaluation": [
            {"id": "crust", "text": "겉·바닥 두께 일정"},
            {"id": "color", "text": "윗면 진한 황금·밑 연갈색"},
            {"id": "filling", "text": "아몬드 고르게·맨홀 없음"},
        ],
        "difficulty": 5,
    },
    {
        "id": "pound_cake",
        "name": "파운드 케이크",
        "category": "cake",
        "examTimeSec": 9000,
        "mixingMethod": "cream",
        "oven": {"top": 200, "bottom": 180, "unit": "celsius", "timeSec": 900, "notes": "2단계: 이후 180/160℃ 20~30분"},
        "fermentation": {},
        "ingredients": [
            {"name": "박력분", "amount": 800, "unit": "g", "category": "flour"},
            {"name": "설탕", "amount": 640, "unit": "g", "category": "sweetener"},
            {"name": "버터", "amount": 640, "unit": "g", "category": "fat"},
            {"name": "유화제", "amount": 16, "unit": "g", "category": "improver"},
            {"name": "소금", "amount": 8, "unit": "g", "category": "salt"},
            {"name": "탈지분유", "amount": 16, "unit": "g", "category": "powder"},
            {"name": "바닐라향", "amount": 4, "unit": "g", "category": "spice"},
            {"name": "베이킹파우더", "amount": 16, "unit": "g", "category": "powder"},
            {"name": "달걀", "amount": 640, "unit": "g", "category": "egg"},
        ],
        "weighNotes": "계량 9분. 비중 0.8±0.05. 파운드틀 4개.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간 30분", "크림법", "반죽온 23℃"]},
            {"title": "반죽", "items": ["비중 0.8±0.05", "U자 팬닝 70%"]},
            {"title": "성형", "items": ["윗면 일자 절개", "뚜껑(지시)"]},
            {"title": "굽기", "items": ["200/180℃ 15분→180/160℃ 20~30분"]},
            {"title": "주요 감점 포인트", "items": ["기공 과다", "4개 불균", "속살 벌어짐 부족"]},
        ],
        "steps": [
            {"title": "01~07. 반죽·팬닝", "description": ["크림화", "가루 접기", "70% U자"], "estimatedTimeSec": 1500},
            {"title": "08~11. 굽기", "description": ["1차 15분", "절개", "2차 20~30분"], "estimatedTimeSec": 2700},
        ],
        "resultEvaluation": [
            {"id": "crumb", "text": "내부 기공 없이 매끈"},
            {"id": "appearance", "text": "4개 대칭·진한 황금"},
            {"id": "split", "text": "가운데 속살 잘 벌어짐"},
        ],
        "difficulty": 4,
    },
    {
        "id": "walnut_pie",
        "name": "호두파이",
        "category": "specialty",
        "examTimeSec": 9000,
        "mixingMethod": "blending",
        "oven": {"top": 180, "bottom": 200, "unit": "celsius", "timeSec": 2100},
        "fermentation": {},
        "ingredients": [
            {"name": "중력분", "amount": 400, "unit": "g", "category": "flour"},
            {"name": "달걀 노른자", "amount": 40, "unit": "g", "category": "egg"},
            {"name": "소금", "amount": 6, "unit": "g", "category": "salt"},
            {"name": "설탕", "amount": 12, "unit": "g", "category": "sweetener"},
            {"name": "생크림", "amount": 48, "unit": "g", "category": "liquid"},
            {"name": "버터", "amount": 160, "unit": "g", "category": "fat"},
            {"name": "물", "amount": 100, "unit": "g", "category": "liquid"},
            {"name": "호두", "amount": 250, "unit": "g", "category": "filling"},
            {"name": "설탕(충전)", "amount": 250, "unit": "g", "category": "sweetener"},
            {"name": "물엿", "amount": 250, "unit": "g", "category": "sweetener"},
            {"name": "계핏가루", "amount": 2.5, "unit": "g", "category": "spice"},
            {"name": "물(충전)", "amount": 100, "unit": "g", "category": "liquid"},
            {"name": "달걀", "amount": 600, "unit": "g", "category": "egg"},
        ],
        "weighNotes": "껍질 계량 7분. 충전은 휴지 중. 손반죽 겹.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["2시간 30분", "블렌딩법", "7개 제조"]},
            {"title": "반죽", "items": ["콩알 버터", "냉장휴지 30분", "과치대 금지"]},
            {"title": "성형", "items": ["물결 가장자리", "충전 층 선명"]},
            {"title": "굽기", "items": ["180/200℃ 30~40분", "아랫불 높게"]},
            {"title": "주요 감점 포인트", "items": ["주저앉음", "윗 터짐", "겹 없음"]},
        ],
        "steps": [
            {"title": "01~06. 껍질", "description": ["계량", "찬물 용해", "버터 다지기", "냉장휴지"], "estimatedTimeSec": 1200},
            {"title": "07~10. 충전", "description": ["호두 구움", "시럽 중탕", "달걀·체거름"], "estimatedTimeSec": 900},
            {"title": "11~15. 성형·굽기", "description": ["팬닝", "물결", "충전", "굽기"], "estimatedTimeSec": 2700},
        ],
        "resultEvaluation": [
            {"id": "structure", "text": "밑·옆 색·함몰 없음"},
            {"id": "uniformity", "text": "7개 두께·모양 동일"},
            {"id": "layers", "text": "껍질 겹·바닥 적정 두께"},
        ],
        "difficulty": 5,
    },
    {
        "id": "black_rice_roll_cake",
        "name": "흑미롤케이크",
        "category": "cake",
        "examTimeSec": 6600,
        "mixingMethod": "sponge",
        "oven": {"top": 180, "bottom": 160, "unit": "celsius", "timeSec": 1050},
        "fermentation": {},
        "ingredients": [
            {"name": "박력쌀가루", "amount": 240, "unit": "g", "category": "flour"},
            {"name": "흑미쌀가루", "amount": 60, "unit": "g", "category": "flour"},
            {"name": "설탕", "amount": 300, "unit": "g", "category": "sweetener"},
            {"name": "달걀", "amount": 465, "unit": "g", "category": "egg"},
            {"name": "소금", "amount": 2, "unit": "g", "category": "salt"},
            {"name": "베이킹파우더", "amount": 2, "unit": "g", "category": "powder"},
            {"name": "우유", "amount": 180, "unit": "g", "category": "liquid"},
            {"name": "생크림", "amount": 150, "unit": "g", "category": "filling"},
        ],
        "weighNotes": "계량 7분. 비중 0.5±0.05. 반죽온 25℃. 밑면이 윗면.",
        "keyPoints": [
            {"title": "시험 정보", "items": ["1시간 50분", "공립법", "반죽온 25℃"]},
            {"title": "반죽", "items": ["달걀 중탕 43℃", "우유 50℃", "비중 0.5±0.05"]},
            {"title": "성형", "items": ["생크림 말기", "좌우 대칭"]},
            {"title": "굽기", "items": ["180/160℃ 15~20분", "펀칭"]},
            {"title": "주요 감점 포인트", "items": ["흑미 뭉침", "갈라짐", "크림 찌그러짐"]},
        ],
        "steps": [
            {"title": "01~08. 시트", "description": ["계량", "중탕 거품", "가루·우유", "팬닝·굽기"], "estimatedTimeSec": 1500},
            {"title": "09~14. 말기", "description": ["냉각·생크림", "뒤집기", "말기"], "estimatedTimeSec": 1200},
        ],
        "resultEvaluation": [
            {"id": "symmetry", "text": "좌우 대칭·크림 약하게 휘핑"},
            {"id": "fill", "text": "크림 균일·롤 풀림 없음"},
            {"id": "surface", "text": "윗면 뭉침·갈라짐 없음"},
        ],
        "difficulty": 4,
    },
]
